name: Format PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.12.x' # you can use 1.12
        channel: 'dev' # optional, default to: 'stable'
    - run: flutter format .
    - uses: stefanzweifel/git-auto-commit-action@v4.1.3
      with:
        commit_message: Apply Auto Formatter
        branch: ${{ github.head_ref }}
