name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: bltavares/actions/dartfmt@master
      with:
        secrets: ${{ secrets.GITHUB_TOKEN }}
